Connected to Python 3.11.3

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
mport pandas as pd
from glob import glob

SyntaxError: invalid syntax (<ipython-input-3-abd59763c58e>, line 1)

In [ ]:
import pandas as pd
from glob import glob

In [ ]:
from glob import glob

In [ ]:
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [ ]:
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [ ]:
single_file_acc

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094
...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108

In [ ]:
single_file_gyro = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

In [ ]:
single_file_gyro

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s)
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500
...,...,...,...,...,...,...
409,1547219424711,2019-01-11T16:10:24.711,16.36,2.195,-1.402,4.268
410,1547219424751,2019-01-11T16:10:24.751,16.40,4.451,-1.220,0.244
411,1547219424791,2019-01-11T16:10:24.791,16.44,7.195,-4.329,6.524
412,1547219424831,2019-01-11T16:10:24.831,16.48,8.963,-1.037,-0.366
413,1547219424871,2019-01-11T16:10:24.871,16.52,-3.476,2.134,-5.305

In [ ]:
files = glob("../../data/raw/MetaMotion/*.csv")

In [ ]:
glob

In [ ]:
files

['../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',

In [ ]:
len(files)

187

In [ ]:
files[0]

'../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [ ]:
participant = f.split("-")[0].replace(data_path, "")

NameError: name 'f' is not defined

In [ ]:
data_path = "../../data/raw/MetaMotion/"

In [ ]:
f = files[0]

In [ ]:
participant = f.split("-")[0].replace(data_path, "")

In [ ]:
lens = f.split("-")[1]

In [ ]:
category = f.split("-")[2].rstrip("123")

In [ ]:
df = pd.read_csv(f)

In [ ]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094
...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108

In [ ]:
df["participant"] = participant

In [ ]:
df["lens"] = lens

In [ ]:
df["category"] = category

In [ ]:
participant

'../../data/raw/MetaMotion\\A'

In [ ]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,lens,category
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,../../data/raw/MetaMotion\A,bench,heavy
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,../../data/raw/MetaMotion\A,bench,heavy
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,../../data/raw/MetaMotion\A,bench,heavy
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,../../data/raw/MetaMotion\A,bench,heavy
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,../../data/raw/MetaMotion\A,bench,heavy
...,...,...,...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091,../../data/raw/MetaMotion\A,bench,heavy
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068,../../data/raw/MetaMotion\A,bench,heavy
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091,../../data/raw/MetaMotion\A,bench,heavy
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085,../../data/raw/MetaMotion\A,bench,heavy
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108,../../data/raw/MetaMotion\A,bench,heavy

In [ ]:
participant

'../../data/raw/MetaMotion\\A'

In [ ]:
lens

'bench'

In [ ]:
category

'heavy'

In [ ]:
acc_df = pd.DataFrame()

In [ ]:
gyr_df = pd.DataFrame()

In [ ]:
acc_set = 1

In [ ]:
gyr_set = 1

In [ ]:
for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123")

In [ ]:
print(label)

NameError: name 'label' is not defined

In [ ]:
for f in files:

SyntaxError: incomplete input (<ipython-input-38-cb1f70c9acaf>, line 1)

In [ ]:
participant = f.split("-")[0].replace(data_path, "")

In [ ]:
lens = f.split("-")[1]

In [ ]:
category = f.split("-")[2].rstrip("123")

In [ ]:
print(label)

NameError: name 'label' is not defined

In [ ]:
label = f.split("-")[1]

In [ ]:
df["label"] = label

In [ ]:
print(participant)

../../data/raw/MetaMotion\E

In [ ]:
print(label)

squat

In [ ]:
print(participant)

../../data/raw/MetaMotion\E

In [ ]:
print(category)

heavy_MetaWear_2019

In [ ]:
ata_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123")
    
    print(category)

heavy
heavy
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy
heavy
heavy
heavy
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium
medium
medium
medium
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
medium
medium
heavy1_MetaWear_2019
heavy1_MetaWear_2019
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy
heavy
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019

In [ ]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123")
    
    print(category)

heavy
heavy
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy
heavy
heavy
heavy
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium
medium
medium
medium
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
medium
medium
heavy1_MetaWear_2019
heavy1_MetaWear_2019
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy
heavy
heavy2_MetaWear_2019
heavy2_MetaWear_2019
heavy
heavy
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium
medium
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
sitting_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
standing_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
medium_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019
heavy_MetaWear_2019

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    print(category)

heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
sitting
sitting
sitting
sitting
standing
standing
standing
standing
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
heavy
heavy
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy
heavy
heavy
sitting
sitting
sitting
sitting
standing
standing
standing
standing
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
heavy
heavy
heavy
heavy

In [ ]:
print(label)

bench

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    print(label)

bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench
bench

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    print(participant)

../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\A
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\B
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\C
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\D
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E
../../data/raw/MetaMotion\E

In [ ]:
df = pd.read_csv(f)

In [ ]:
df = pd.read_csv(f)
df["participant"] = participant
df["label"] = label
df["category"] = category

In [ ]:
df["participant"] = participant

In [ ]:
df["label"] = label

In [ ]:
df["category"] = category

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    df = pd.read_csv(f)
    
    df["participant"] = participant
    df["label"] = label
    df["category"] = category

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
f

'../../data/raw/MetaMotion\\E-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [ ]:
files

['../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',

In [ ]:
f = files[1]

In [ ]:
1

1

In [ ]:
files

['../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../../data/raw/MetaMotion\\E-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../../data/raw/MetaMotion\\E-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])

In [ ]:
if "Accelerometer" in f:

SyntaxError: incomplete input (<ipython-input-74-743720c1e7ab>, line 1)

In [ ]:
acc_df = pd.concat([acc_df, df])

In [ ]:
if "Gyroscope" in f:

SyntaxError: incomplete input (<ipython-input-76-6901137ee1d5>, line 1)

In [ ]:
gyr_df = pd.concat([gyr_df, df])

In [ ]:
if "Gyroscope" in f:
    gyr_df = pd.concat([gyr_df, df])

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,../../data/raw/MetaMotion\E,bench,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,../../data/raw/MetaMotion\E,bench,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,../../data/raw/MetaMotion\E,bench,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,../../data/raw/MetaMotion\E,bench,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,../../data/raw/MetaMotion\E,bench,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,bench,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,bench,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,bench,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,bench,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,bench,heavy

In [ ]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,../../data/raw/MetaMotion\E,bench,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,../../data/raw/MetaMotion\E,bench,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,../../data/raw/MetaMotion\E,bench,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,../../data/raw/MetaMotion\E,bench,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,../../data/raw/MetaMotion\E,bench,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,bench,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,bench,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,bench,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,bench,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,bench,heavy

In [ ]:
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [ ]:
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

single_file_gyro = pd.read_csv("../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")
# --------------------------------------------------------------
# List all data in data/raw/MetaMotion
# --------------------------------------------------------------

files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

# --------------------------------------------------------------
# Extract features from filename
# --------------------------------------------------------------

data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    lens = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    df = pd.read_csv(f)
    df["participant"] = participant
    df["label"] = label
    df["category"] = category

if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])
    
if "Gyroscope" in f:
    gyr_df = pd.concat([gyr_df, df])

In [ ]:
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    
    df = pd.read_csv(f)
    df["participant"] = participant
    df["label"] = label
    df["category"] = category

if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])
    
if "Gyroscope" in f:
    gyr_df = pd.concat([gyr_df, df])

In [ ]:
acc_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
acc_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
acc_df = pd.DataFrame()

In [ ]:
gyr_df = pd.DataFrame()

In [ ]:
acc_set = 1

In [ ]:
gyr_set = 1

In [ ]:
participant = f.split("-")[0].replace(data_path, "")

In [ ]:
label = f.split("-")[1]

In [ ]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [ ]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [ ]:
df = pd.read_csv(f)

In [ ]:
df["participant"] = participant

In [ ]:
df["label"] = label

In [ ]:
df["category"] = category

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])

In [ ]:
if "Gyroscope" in f:
    gyr_df = pd.concat([gyr_df, df])

In [ ]:
acc_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,../../data/raw/MetaMotion\E,squat,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,../../data/raw/MetaMotion\E,squat,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,../../data/raw/MetaMotion\E,squat,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,../../data/raw/MetaMotion\E,squat,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,../../data/raw/MetaMotion\E,squat,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,squat,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,squat,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,squat,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,squat,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,squat,heavy

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,../../data/raw/MetaMotion\E,squat,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,../../data/raw/MetaMotion\E,squat,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,../../data/raw/MetaMotion\E,squat,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,../../data/raw/MetaMotion\E,squat,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,../../data/raw/MetaMotion\E,squat,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,squat,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,squat,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,squat,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,squat,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,squat,heavy

In [ ]:
if "Accelerometer" in f:
    acc_df = pd.concat([acc_df, df])
    
if "Gyroscope" in f:
    gyr_df = pd.concat([gyr_df, df])

In [ ]:
acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547666043834,2019-01-16 20:14:03.834,0.00,-10.549,1.646,-1.280,../../data/raw/MetaMotion\E,squat,heavy
1,1547666043874,2019-01-16 20:14:03.874,0.04,-8.963,1.524,-0.732,../../data/raw/MetaMotion\E,squat,heavy
2,1547666043914,2019-01-16 20:14:03.914,0.08,-2.378,-1.280,0.305,../../data/raw/MetaMotion\E,squat,heavy
3,1547666043954,2019-01-16 20:14:03.954,0.12,-2.500,0.732,-1.829,../../data/raw/MetaMotion\E,squat,heavy
4,1547666043994,2019-01-16 20:14:03.994,0.16,-11.037,3.780,-2.561,../../data/raw/MetaMotion\E,squat,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,squat,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,squat,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,squat,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,squat,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,squat,heavy

In [ ]:
acc_df = pd.DataFrame()

In [ ]:
gyr_df = pd.DataFrame()

In [ ]:
acc_set = 1

In [ ]:
gyr_set = 1

In [ ]:
for f in files:

SyntaxError: incomplete input (<ipython-input-115-cb1f70c9acaf>, line 1)

In [ ]:
for f in files:
    
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df["participant"] = participant
    df["label"] = label
    df["category"] = category

    if "Accelerometer" in f:
        acc_df = pd.concat([acc_df, df])

    if "Gyroscope" in f:
        gyr_df = pd.concat([gyr_df, df])

In [ ]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,../../data/raw/MetaMotion\A,bench,heavy
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,../../data/raw/MetaMotion\A,bench,heavy
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,../../data/raw/MetaMotion\A,bench,heavy
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,../../data/raw/MetaMotion\A,bench,heavy
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,../../data/raw/MetaMotion\A,bench,heavy
...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,squat,heavy
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,../../data/raw/MetaMotion\E,squat,heavy
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,squat,heavy
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,squat,heavy
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,squat,heavy

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,../../data/raw/MetaMotion\A,bench,heavy
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,../../data/raw/MetaMotion\A,bench,heavy
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,../../data/raw/MetaMotion\A,bench,heavy
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,../../data/raw/MetaMotion\A,bench,heavy
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,../../data/raw/MetaMotion\A,bench,heavy
...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,../../data/raw/MetaMotion\E,squat,heavy
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,../../data/raw/MetaMotion\E,squat,heavy
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,../../data/raw/MetaMotion\E,squat,heavy
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,../../data/raw/MetaMotion\E,squat,heavy
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,../../data/raw/MetaMotion\E,squat,heavy

In [ ]:
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1 
gyr_set = 1

In [ ]:
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1 
gyr_set = 1

In [ ]:
for f in files:
    
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df["participant"] = participant
    df["label"] = label
    df["category"] = category

    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])

    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [ ]:
acc_df = pd.concat([acc_df, df])

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s)
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,-1.707,-0.671,1.585
488,1547666063354,2019-01-16 20:14:23.354,19.52,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,0.915,0.305,2.988
489,1547666063394,2019-01-16 20:14:23.394,19.56,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,5.854,-2.561,1.463
490,1547666063434,2019-01-16 20:14:23.434,19.60,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,4.268,0.549,-0.305
491,1547666063474,2019-01-16 20:14:23.474,19.64,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,-1.098,1.768,-0.122

In [ ]:
acc_df.info()

<class 'pandas.DataFrame'>
Index: 24070 entries, 0 to 491
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   epoch (ms)      24070 non-null  int64
 1   time (01:00)    24070 non-null  str
 2   elapsed (s)     24070 non-null  float64
 3   x-axis (g)      23578 non-null  float64
 4   y-axis (g)      23578 non-null  float64
 5   z-axis (g)      23578 non-null  float64
 6   participant     24070 non-null  str
 7   label           24070 non-null  str
 8   category        24070 non-null  str
 9   set             24070 non-null  int64
 10  x-axis (deg/s)  492 non-null    float64
 11  y-axis (deg/s)  492 non-null    float64
 12  z-axis (deg/s)  492 non-null    float64
dtypes: float64(7), int64(2), str(4)
memory usage: 2.6 MB

In [ ]:
pd.to_datetime(df["epoch"], unit="ms")

KeyError: 'epoch'

In [ ]:
acc_df.info()

pd.to_datetime(df["epoch"], unit="ms")

<class 'pandas.DataFrame'>
Index: 24070 entries, 0 to 491
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   epoch (ms)      24070 non-null  int64
 1   time (01:00)    24070 non-null  str
 2   elapsed (s)     24070 non-null  float64
 3   x-axis (g)      23578 non-null  float64
 4   y-axis (g)      23578 non-null  float64
 5   z-axis (g)      23578 non-null  float64
 6   participant     24070 non-null  str
 7   label           24070 non-null  str
 8   category        24070 non-null  str
 9   set             24070 non-null  int64
 10  x-axis (deg/s)  492 non-null    float64
 11  y-axis (deg/s)  492 non-null    float64
 12  z-axis (deg/s)  492 non-null    float64
dtypes: float64(7), int64(2), str(4)
memory usage: 2.6 MB

KeyError: 'epoch'

In [ ]:
pd.to_datetime(acc_df["epoch"], unit="ms")

KeyError: 'epoch'

In [ ]:
pd.to_datetime(df["epoch (ms)"], unit="ms")

0     2019-01-16 19:14:03.834
1     2019-01-16 19:14:03.874
2     2019-01-16 19:14:03.914
3     2019-01-16 19:14:03.954
4     2019-01-16 19:14:03.994
                ...
487   2019-01-16 19:14:23.314
488   2019-01-16 19:14:23.354
489   2019-01-16 19:14:23.394
490   2019-01-16 19:14:23.434
491   2019-01-16 19:14:23.474
Name: epoch (ms), Length: 492, dtype: datetime64[ms]

In [ ]:
df["time (01:00:00)"]

KeyError: 'time (01:00:00)'

In [ ]:
df["time (01:00)"]

0      2019-01-16 20:14:03.834
1      2019-01-16 20:14:03.874
2      2019-01-16 20:14:03.914
3      2019-01-16 20:14:03.954
4      2019-01-16 20:14:03.994
                ...
487    2019-01-16 20:14:23.314
488    2019-01-16 20:14:23.354
489    2019-01-16 20:14:23.394
490    2019-01-16 20:14:23.434
491    2019-01-16 20:14:23.474
Name: time (01:00), Length: 492, dtype: str

In [ ]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

In [ ]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s)
epoch (ms),,,,,,,,,,,,,
2019-01-11 15:10:08.431,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
2019-01-11 15:10:08.511,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
2019-01-11 15:10:08.591,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
2019-01-11 15:10:08.671,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
2019-01-11 15:10:08.751,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,../../data/raw/MetaMotion\A,bench,heavy,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,1547666063314,2019-01-16 20:14:23.314,19.48,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,-1.707,-0.671,1.585
2019-01-16 19:14:23.354,1547666063354,2019-01-16 20:14:23.354,19.52,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,0.915,0.305,2.988
2019-01-16 19:14:23.394,1547666063394,2019-01-16 20:14:23.394,19.56,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,5.854,-2.561,1.463
2019-01-16 19:14:23.434,1547666063434,2019-01-16 20:14:23.434,19.60,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,4.268,0.549,-0.305
2019-01-16 19:14:23.474,1547666063474,2019-01-16 20:14:23.474,19.64,NaN,NaN,NaN,../../data/raw/MetaMotion\E,squat,heavy,93,-1.098,1.768,-0.122

In [ ]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

In [ ]:
del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s) "]

del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]      
del gyr_df["elapsed (s) "]

KeyError: 'elapsed (s) '

In [ ]:
del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]      
del gyr_df["elapsed (s)"]

KeyError: 'epoch (ms)'

In [ ]:
participant = f.split("-")[0].replace(data_path, "").rstrip("data_path")

In [ ]:
data_path = "../../data/raw/MetaMotion/"
f = files[1]

participant = f.split("-")[0].replace(data_path, "").rstrip("data_path")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1 
gyr_set = 1


for f in files:
    
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df["participant"] = participant
    df["label"] = label
    df["category"] = category

    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])

    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])
        
# --------------------------------------------------------------
# Working with datetimes
# --------------------------------------------------------------
acc_df.info()

pd.to_datetime(df["epoch (ms)"], unit="ms") 
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms") 
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]      
del gyr_df["elapsed (s)"]

<class 'pandas.DataFrame'>
Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  str
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  str
 7   label         23578 non-null  str
 8   category      23578 non-null  str
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), str(4)
memory usage: 2.0 MB

In [ ]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,../../data/raw/MetaMotion\A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,../../data/raw/MetaMotion\E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,../../data/raw/MetaMotion\E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,../../data/raw/MetaMotion\E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,../../data/raw/MetaMotion\E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,../../data/raw/MetaMotion\E,squat,heavy,94

In [ ]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,../../data/raw/MetaMotion\A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,../../data/raw/MetaMotion\A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,../../data/raw/MetaMotion\E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,../../data/raw/MetaMotion\E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,../../data/raw/MetaMotion\E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,../../data/raw/MetaMotion\E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,../../data/raw/MetaMotion\E,squat,heavy,93

In [ ]:
data_path = "../../data/raw/MetaMotion\"

SyntaxError: unterminated string literal (detected at line 1) (<ipython-input-140-1860caf75828>, line 1)

In [ ]:
data_path = "../../data/raw/MetaMotion\\"

In [ ]:
data_path = "../../data/raw/MetaMotion\\"
f = files[1]

participant = f.split("-")[0].replace(data_path, "")
label = f.split("-")[1]
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label       
df["category"] = category

# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1 
gyr_set = 1


for f in files:
    
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(f)

    df["participant"] = participant
    df["label"] = label
    df["category"] = category

    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])

    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])
        
# --------------------------------------------------------------
# Working with datetimes
# --------------------------------------------------------------
acc_df.info()

pd.to_datetime(df["epoch (ms)"], unit="ms") 
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms") 
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]      
del gyr_df["elapsed (s)"]

<class 'pandas.DataFrame'>
Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  str
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  str
 7   label         23578 non-null  str
 8   category      23578 non-null  str
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), str(4)
memory usage: 2.0 MB

In [ ]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [ ]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [ ]:
acc_df.info()

pd.to_datetime(df["epoch (ms)"], unit="ms") 
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms") 
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

<class 'pandas.DataFrame'>
DatetimeIndex: 23578 entries, 2019-01-11 15:10:08.431000 to 2019-01-16 19:14:23.409000
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   x-axis (g)   23578 non-null  float64
 1   y-axis (g)   23578 non-null  float64
 2   z-axis (g)   23578 non-null  float64
 3   participant  23578 non-null  str
 4   label        23578 non-null  str
 5   category     23578 non-null  str
 6   set          23578 non-null  int64
dtypes: float64(3), int64(1), str(3)
memory usage: 1.4 MB

KeyError: 'epoch (ms)'

In [ ]:
acc_df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 23578 entries, 2019-01-11 15:10:08.431000 to 2019-01-16 19:14:23.409000
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   x-axis (g)   23578 non-null  float64
 1   y-axis (g)   23578 non-null  float64
 2   z-axis (g)   23578 non-null  float64
 3   participant  23578 non-null  str
 4   label        23578 non-null  str
 5   category     23578 non-null  str
 6   set          23578 non-null  int64
dtypes: float64(3), int64(1), str(3)
memory usage: 1.4 MB

In [ ]:
pd.to_datetime(df["epoch (ms)"], unit="ms")

0     2019-01-16 19:14:03.834
1     2019-01-16 19:14:03.874
2     2019-01-16 19:14:03.914
3     2019-01-16 19:14:03.954
4     2019-01-16 19:14:03.994
                ...
487   2019-01-16 19:14:23.314
488   2019-01-16 19:14:23.354
489   2019-01-16 19:14:23.394
490   2019-01-16 19:14:23.434
491   2019-01-16 19:14:23.474
Name: epoch (ms), Length: 492, dtype: datetime64[ms]

In [ ]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

KeyError: 'epoch (ms)'

In [ ]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

KeyError: 'epoch (ms)'

In [ ]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

KeyError: 'epoch (ms)'

In [ ]:
pd.to_datetime(df["epoch (ms)"], unit="ms")

0     2019-01-16 19:14:03.834
1     2019-01-16 19:14:03.874
2     2019-01-16 19:14:03.914
3     2019-01-16 19:14:03.954
4     2019-01-16 19:14:03.994
                ...
487   2019-01-16 19:14:23.314
488   2019-01-16 19:14:23.354
489   2019-01-16 19:14:23.394
490   2019-01-16 19:14:23.434
491   2019-01-16 19:14:23.474
Name: epoch (ms), Length: 492, dtype: datetime64[ms]

In [ ]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

KeyError: 'epoch (ms)'

In [ ]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [ ]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [ ]:
files = glob("../../data/raw/MetaMotion/*.csv")

def read_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()

    acc_set = 1 
    gyr_set = 1

    for f in files:
    
        participant = f.split("-")[0].replace(data_path, "")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

        df = pd.read_csv(f)

        df["participant"] = participant
        df["label"] = label
        df["category"] = category

        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])

        if "Gyroscope" in f:
            df["set"] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])
            
    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")   
    
    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]      
    del acc_df["elapsed (s)"]
    
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]      
    del gyr_df["elapsed (s)"]
    
    return acc_df, gyr_df

In [ ]:
acc_df, gyr_df = read_data_from_files(files)

NameError: name 'read_data_from_files' is not defined

In [ ]:
files = glob("../../data/raw/MetaMotion/*.csv")

def read_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()

    acc_set = 1 
    gyr_set = 1

    for f in files:
    
        participant = f.split("-")[0].replace(data_path, "")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

        df = pd.read_csv(f)

        df["participant"] = participant
        df["label"] = label
        df["category"] = category

        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])

        if "Gyroscope" in f:
            df["set"] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])
            
    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")   
    
    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]      
    del acc_df["elapsed (s)"]
    
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]      
    del gyr_df["elapsed (s)"]
    
    return acc_df, gyr_df

acc_df, gyr_df = read_data_from_files(files)

NameError: name 'read_data_from_files' is not defined

In [ ]:
acc_df, gyr_df = read_files(files)

In [ ]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [ ]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [ ]:
pd.concat([acc_df, gyr_df], axis=1)

<ipython-input-161-5759e21e66bf>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  pd.concat([acc_df, gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,E,row,medium,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,E,row,medium,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,E,row,medium,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,E,row,medium,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,E,row,medium,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

<ipython-input-162-6203e873d15f>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

<ipython-input-163-0ee025073f40>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

In [ ]:
data_merged.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,1.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,1.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,1.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,1.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,1.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,24.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,24.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,24.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,24.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,24.0

In [ ]:
data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"]

In [ ]:
data_merged

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_merged[:100].resample(rule="S")

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged[:100].resample(rule="S").mean()

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"
    ] 

# --------------------------------------------------------------
# Resample data (frequency conversion)
# --------------------------------------------------------------

# Accelerometer:    12.500HZ
# Gyroscope:        25.000Hz

data_merged[:100].resample(rule="S").mean()

<ipython-input-169-6329cfad664a>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"]

<ipython-input-170-09c4f7e4ef37>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

In [ ]:
data_merged[:100].resample(rule="S").mean()

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_resampled = data_merged.resample(rule="S").mean()

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged[:100].resample("S").mean() # Resample to 10Hz (100ms intervals)

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged[:100].resample(rule="S").mean() # Resample to 10Hz (100ms intervals)

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"] 

# Ensure the index is a DatetimeIndex for resampling
data_merged.index = acc_df.index

# --------------------------------------------------------------
# Resample data (frequency conversion)
# --------------------------------------------------------------

# Accelerometer:    12.500HZ
# Gyroscope:        25.000Hz

data_merged[:100].resample(rule="S").mean()

<ipython-input-175-f5c36ad007da>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

ValueError: Length mismatch: Expected axis has 69677 elements, new values have 23578 elements

In [ ]:
data_merged.index = acc_df.index

ValueError: Length mismatch: Expected axis has 69677 elements, new values have 23578 elements

In [ ]:
data_merged[:100].resample(rule="S").mean() # Resample to 10Hz (100ms intervals)

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"] 



# --------------------------------------------------------------
# Resample data (frequency conversion)
# --------------------------------------------------------------

# Accelerometer:    12.500HZ
# Gyroscope:        25.000Hz

data_merged[:100].resample(rule="S").mean()

<ipython-input-178-351519b24b9a>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"]

<ipython-input-179-09c4f7e4ef37>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

In [ ]:
data_merged[:100].resample(rule="S")

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_merged.resample(rule="S").mean()

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [ ]:
data_resampled = data_merged.resample(rule="200ms").mean()

TypeError: dtype 'str' does not support operation 'mean'

In [ ]:
data_resampled = data_merged[:1000].resample(rule="200ms").mean()

TypeError: dtype 'str' does not support operation 'mean'

In [ ]:
sampling = {  "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "label", 
    "category", 
    "participant",
    "set"}

In [ ]:
sampling = {  "acc_x": "mean", 
    "acc_y": "mean", 
    "acc_z": "mean", 
    "gyr_x": "mean", 
    "gyr_y": "mean", 
    "gyr_z": "mean", 
    "label": "last", 
    "category": "last", 
    "participant": "last",
    "set": "last",
    }

In [ ]:
data_resampled = data_merged[:1000].resample(rule="200ms").mean()

TypeError: dtype 'str' does not support operation 'mean'

In [ ]:
data_resampled = data_merged.resample(rule="200ms").apply(sampling)

In [ ]:
data_merged.resample(rule="200ms").apply(sampling)

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.6955,-1.7985,4.5735,B,bench,heavy,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.0122,-0.4270,-1.6218,B,bench,heavy,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:12.800,-0.041000,-1.247000,-0.074667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.000,-0.039000,-1.037500,-0.043500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.200,-0.050667,-1.009667,-0.042667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.400,-0.040000,-1.033000,-0.029500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.600,-0.044000,-1.029000,-0.044000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
days = [g for n, g in data_merged.groupby(pd.Grouper(freq="D"))]

In [ ]:
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])

In [ ]:
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])

In [ ]:
data_resampled

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30.0
2019-01-11 15:08:05.800,-0.024000,0.957000,-0.073500,8.0610,-4.5244,-2.0730,B,bench,heavy,30.0
2019-01-11 15:08:06.000,-0.028000,0.957667,-0.115000,2.4390,-1.5486,-3.6098,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.000,-0.048000,-1.041500,-0.076500,1.4146,-5.6218,0.2926,E,row,medium,90.0
2019-01-20 17:33:27.200,-0.037000,-1.030333,-0.053333,-2.7684,-0.5854,2.2440,E,row,medium,90.0
2019-01-20 17:33:27.400,-0.060000,-1.031000,-0.082000,2.8416,-5.1342,-0.1220,E,row,medium,90.0
2019-01-20 17:33:27.600,-0.038667,-1.025667,-0.044667,-0.2318,0.2562,1.1220,E,row,medium,90.0
2019-01-20 17:33:27.800,-0.044000,-1.034000,-0.059000,1.0980,-4.0240,0.9760,E,row,medium,90.0

In [ ]:
data_resampled.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   label        9009 non-null   str
 7   category     9009 non-null   str
 8   participant  9009 non-null   str
 9   set          9009 non-null   float64
dtypes: float64(7), str(3)
memory usage: 774.2 KB

In [ ]:
data_resampled["set"] = data_resampled["set"].astype(int)

In [ ]:
data_resampled.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   label        9009 non-null   str
 7   category     9009 non-null   str
 8   participant  9009 non-null   str
 9   set          9009 non-null   int64
dtypes: float64(6), int64(1), str(3)
memory usage: 774.2 KB

In [ ]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")

In [ ]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1) 

data_merged.columns = [
    "acc_x", 
    "acc_y", 
    "acc_z", 
    "gyr_x", 
    "gyr_y", 
    "gyr_z", 
    "participant",
    "label", 
    "category", 
    "set"]

<ipython-input-197-5dd8f7745e94>:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

In [ ]:
sampling = {  "acc_x": "mean", 
    "acc_y": "mean", 
    "acc_z": "mean", 
    "gyr_x": "mean", 
    "gyr_y": "mean", 
    "gyr_z": "mean", 
    "participant": "last",
    "label": "last", 
    "category": "last", 
    "set": "last",

SyntaxError: incomplete input (<ipython-input-198-98ca9d24c1ea>, line 10)

In [ ]:
sampling = {  "acc_x": "mean", 
    "acc_y": "mean", 
    "acc_z": "mean", 
    "gyr_x": "mean", 
    "gyr_y": "mean", 
    "gyr_z": "mean", 
    "participant": "last",
    "label": "last", 
    "category": "last", 
    "set": "last"
    }

In [ ]:
data_merged.resample(rule="200ms").apply(sampling)

#split by day 
days = [g for n, g in data_merged.groupby(pd.Grouper(freq="D"))]
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])

data_resampled["set"] = data_resampled["set"].astype(int)
data_resampled.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   str
 7   label        9009 non-null   str
 8   category     9009 non-null   str
 9   set          9009 non-null   int64
dtypes: float64(6), int64(1), str(3)
memory usage: 774.2 KB

In [ ]:
data_resampled

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30
2019-01-11 15:08:05.800,-0.024000,0.957000,-0.073500,8.0610,-4.5244,-2.0730,B,bench,heavy,30
2019-01-11 15:08:06.000,-0.028000,0.957667,-0.115000,2.4390,-1.5486,-3.6098,B,bench,heavy,30
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.000,-0.048000,-1.041500,-0.076500,1.4146,-5.6218,0.2926,E,row,medium,90
2019-01-20 17:33:27.200,-0.037000,-1.030333,-0.053333,-2.7684,-0.5854,2.2440,E,row,medium,90
2019-01-20 17:33:27.400,-0.060000,-1.031000,-0.082000,2.8416,-5.1342,-0.1220,E,row,medium,90
2019-01-20 17:33:27.600,-0.038667,-1.025667,-0.044667,-0.2318,0.2562,1.1220,E,row,medium,90
2019-01-20 17:33:27.800,-0.044000,-1.034000,-0.059000,1.0980,-4.0240,0.9760,E,row,medium,90

In [ ]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")